services:
  sesion:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'sesions'
      MYSQL_USER: 'enoc'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: '1234'
    volumes:
      # Montamos un volumen para MySQL para no perder los datos de bd
      - ./database:/var/lib/mysql
    expose:
      - 3310
    ports:
      - 3310:3306
    platform: linux/x86_64